# Generated by Django 3.2.13 on 2022-07-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20220701_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquesaida',
            options={'verbose_name': 'estoque saída', 'verbose_name_plural': 'estoque saída'},
        ),
    ]
