# Generated by Django 3.2.13 on 2022-07-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('-produto',)},
        ),
    ]
